export type GlossaryTerm = {
  term: string;
  body: string;
  href: string;
  label: string;
};

export const glossaryTerms: GlossaryTerm[] = [
  { term: "Manapickスコア", body: "学習動画を7軸35点で見るための独自スコアです。視聴前の期待値をそろえる目的で使います。", href: "/about-score/", label: "採点方法" },
  { term: "7軸35点", body: "実用性、正確性・鮮度、分かりやすさなど7項目を各5点で確認するManapickの採点形式です。", href: "/about-score/", label: "採点方法" },
  { term: "視聴確認済み", body: "運営者が実際に動画を見て、タイトルと内容の一致、学習用途としての品質を確認した状態です。", href: "/about-score/", label: "採点方法" },
  { term: "ロードマップ", body: "初級から中級、上級へ進む順番をまとめた学習ルートです。何から見るか迷う時間を減らします。", href: "/#roadmap", label: "ロードマップ" },
  { term: "初級", body: "前提知識が少なくても見られる入口の動画です。全体像や基本操作を確認する段階です。", href: "/about-score/#level-definitions", label: "レベル定義" },
  { term: "中級", body: "基礎を一通り触れた人が、応用や体系化へ進むための動画です。", href: "/about-score/#level-definitions", label: "レベル定義" },
  { term: "上級", body: "実務応用、試験対策、専門特化など、より具体的な目的に合わせて見る動画です。", href: "/about-score/#level-definitions", label: "レベル定義" },
  { term: "生成AI", body: "文章、画像、音声、コードなどを生成するAIです。仕事の下書きや調査補助にも使われます。", href: "/genre/ai/", label: "生成AI" },
  { term: "ChatGPT", body: "文章作成、要約、相談、アイデア出しなどに使われる対話型AIです。", href: "/genre/ai/", label: "生成AI動画" },
  { term: "Claude", body: "長文読解や文章整理に強みがある対話型AIです。用途に応じてChatGPTなどと使い分けます。", href: "/genre/ai/", label: "生成AI動画" },
  { term: "Gemini", body: "GoogleのAIで、検索や画像、Google系サービスとの連携を確認したいときに候補になります。", href: "/genre/ai/", label: "生成AI動画" },
  { term: "プロンプト", body: "AIに出す指示文です。目的、条件、出力形式を具体的に書くほど結果が安定します。", href: "/guide/generative-ai/", label: "生成AIガイド" },
  { term: "プロンプトエンジニアリング", body: "AIへの指示を設計し、回答の質を安定させる考え方です。", href: "/genre/ai/", label: "生成AI" },
  { term: "AI資格", body: "AIの基礎知識や活用理解を問う資格・検定の総称として扱っています。", href: "/genre/shikaku/", label: "資格" },
  { term: "Python", body: "データ分析、Web開発、自動化などで広く使われるプログラミング言語です。", href: "/guide/python/", label: "Pythonガイド" },
  { term: "Web開発", body: "WebサイトやWebアプリを作る学習領域です。HTML/CSS、JavaScript、サーバー側の知識を含みます。", href: "/genre/prog/", label: "プログラミング" },
  { term: "アプリ開発", body: "スマホアプリやWebアプリを作る学習領域です。小さく動くものを作りながら学ぶのが近道です。", href: "/genre/prog/", label: "プログラミング" },
  { term: "インフラ", body: "サーバー、ネットワーク、クラウドなど、サービスを動かす土台に関する領域です。", href: "/genre/prog/", label: "プログラミング" },
  { term: "動画編集", body: "素材を切る、音を整える、テロップを入れる、書き出すといった制作作業です。", href: "/guide/video-editing/", label: "動画編集ガイド" },
  { term: "Premiere Pro", body: "動画編集で使われるAdobeの編集ソフトです。仕事や長尺編集で触れる機会があります。", href: "/genre/video/", label: "動画編集動画" },
  { term: "CapCut", body: "短尺動画やSNS向け編集で使われる編集ツールです。無料で始めやすい選択肢です。", href: "/genre/video/", label: "動画編集動画" },
  { term: "After Effects", body: "モーショングラフィックスや合成表現で使われるAdobeのツールです。", href: "/genre/video/", label: "動画編集動画" },
  { term: "英会話", body: "聞く、話す、発音、表現を組み合わせて英語でやり取りする学習領域です。", href: "/guide/english/", label: "英語ガイド" },
  { term: "TOEIC", body: "英語の聞く・読む力を測る試験です。学習の進捗を数字で確認する目的にも使えます。", href: "/genre/english/", label: "英語動画" },
  { term: "発音", body: "英語の音の出し方や聞き取りに関わる学習です。早い段階で触れると聞き取りにも役立ちます。", href: "/genre/english/", label: "英語動画" },
  { term: "ビジネス英語", body: "会議、メール、プレゼンなど仕事で使う英語表現の学習領域です。", href: "/genre/english/", label: "英語動画" },
  { term: "Excel", body: "表計算、集計、資料作成、データ分析で使われる業務ツールです。", href: "/genre/data/", label: "データ分析動画" },
  { term: "データ分析", body: "データを整理し、傾向や判断材料を見つける学習領域です。", href: "/guide/excel-data/", label: "データ分析ガイド" },
  { term: "Power Query", body: "ExcelやPower BIでデータ取得・整形を自動化する機能です。繰り返し作業の削減に向いています。", href: "/guide/excel-data/", label: "Excelデータ分析" },
  { term: "BI", body: "Business Intelligenceの略で、データを可視化して業務判断に使う考え方やツール群です。", href: "/genre/data/", label: "データ分析動画" },
  { term: "データサイエンス", body: "統計、プログラミング、業務理解を組み合わせてデータから知見を得る領域です。", href: "/genre/data/", label: "データ分析" },
  { term: "SEO", body: "検索エンジンから見つけてもらいやすくするためのサイト改善です。", href: "/genre/marke/", label: "Webマーケ動画" },
  { term: "広告運用", body: "Web広告を配信し、結果を見ながら改善していく仕事・学習領域です。", href: "/genre/marke/", label: "Webマーケ動画" },
  { term: "SNS運用", body: "SNSで情報発信や集客を行い、投稿内容や反応を改善していく領域です。", href: "/genre/marke/", label: "Webマーケ動画" },
  { term: "Office・資料作成", body: "Word、Excel、PowerPointなどを使い、仕事の文書や資料を整える領域です。", href: "/guide/office-skills/", label: "Officeガイド" },
  { term: "Word", body: "文書作成に使うOfficeツールです。社内文書や申請書などの整形で役立ちます。", href: "/genre/biz/", label: "Office動画" },
  { term: "PowerPoint", body: "プレゼン資料や説明資料を作るツールです。構成と見せ方の両方を学ぶと使いやすくなります。", href: "/genre/biz/", label: "Office動画" },
  { term: "思考法", body: "情報整理、問題分解、意思決定など、仕事の考え方を整える学習領域です。", href: "/genre/biz/", label: "Office動画" },
  { term: "資格学習", body: "試験範囲、学習順、過去問演習を組み合わせて進める学習です。", href: "/guide/certification/", label: "資格ガイド" },
  { term: "ITパスポート", body: "ITの基礎知識を幅広く問う国家試験です。非エンジニアのIT入門にも使われます。", href: "/genre/shikaku/", label: "資格動画" },
  { term: "基本情報技術者", body: "ITエンジニアの基礎知識を問う国家試験です。プログラミングや設計の基礎も含みます。", href: "/genre/shikaku/", label: "資格動画" },
  { term: "宅建", body: "不動産取引に関する国家資格です。法律用語が多いため、全体像から入ると学びやすくなります。", href: "/genre/shikaku/", label: "資格動画" },
  { term: "登録販売者", body: "一般用医薬品の販売に関わる資格です。暗記と理解の順番を分けると進めやすい領域です。", href: "/genre/shikaku/", label: "資格動画" },
  { term: "医療事務", body: "医療機関の受付や会計、診療報酬に関わる学習領域です。", href: "/genre/shikaku/", label: "資格動画" },
  { term: "MOS", body: "Microsoft Office製品の操作スキルを問う資格です。仕事の実務操作と相性があります。", href: "/genre/shikaku/", label: "資格動画" },
  { term: "簿記", body: "会社のお金の流れを記録・整理する会計の基礎です。資格学習にも実務理解にもつながります。", href: "/guide/bookkeeping/", label: "会計資格ガイド" },
  { term: "FP", body: "家計、保険、税金、投資など生活のお金を幅広く扱う資格・学習領域です。", href: "/genre/kaikei/", label: "会計資格動画" },
  { term: "中小企業診断士", body: "経営、財務、運営、法務などを幅広く学ぶ国家資格です。", href: "/genre/kaikei/", label: "会計資格動画" },
  { term: "NISA", body: "投資で得た利益が一定範囲で非課税になる制度です。制度理解とリスク確認が大切です。", href: "/genre/money/", label: "お金・投資動画" },
  { term: "家計管理", body: "収入、支出、貯蓄、固定費を見える化して生活のお金を整えることです。", href: "/genre/money/", label: "お金・投資動画" },
  { term: "投資", body: "将来のために資産を運用する行為です。Manapickでは特定銘柄の推奨ではなく学習動画を紹介します。", href: "/genre/money/", label: "お金・投資動画" },
  { term: "情報商材誘導", body: "高額教材やサービスへ強く誘導する表現です。Manapickでは学習判断を歪めるものは不採用にします。", href: "/about-score/", label: "除外方針" },
  { term: "誇大表現", body: "短期間で必ず成果が出るように見せる表現です。Manapickでは成果保証に見える表現を避けます。", href: "/disclaimer/", label: "免責事項" },
  { term: "公式埋め込み", body: "YouTubeの公式プレーヤーを使って動画を表示する方法です。再配布やダウンロードとは異なります。", href: "/privacy/", label: "ポリシー" }
];
